
package it.unitn.laboratory.datawarehouse;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebServiceServer", targetNamespace = "http://datawarehouse.laboratory.unitn.it", wsdlLocation = "file:/C:/Users/Michele/workspace/ESBMediator/src/DataConsumerWSDL.wsdl")
public class WebServiceServer_Service
    extends Service
{

    private final static URL WEBSERVICESERVER_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(it.unitn.laboratory.datawarehouse.WebServiceServer_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = it.unitn.laboratory.datawarehouse.WebServiceServer_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/Michele/workspace/ESBMediator/src/DataConsumerWSDL.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/Michele/workspace/ESBMediator/src/DataConsumerWSDL.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICESERVER_WSDL_LOCATION = url;
    }

    public WebServiceServer_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceServer_Service() {
        super(WEBSERVICESERVER_WSDL_LOCATION, new QName("http://datawarehouse.laboratory.unitn.it", "WebServiceServer"));
    }

    /**
     * 
     * @return
     *     returns WebServiceServer
     */
    @WebEndpoint(name = "WebServiceSOAP")
    public WebServiceServer getWebServiceSOAP() {
        return super.getPort(new QName("http://datawarehouse.laboratory.unitn.it", "WebServiceSOAP"), WebServiceServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceServer
     */
    @WebEndpoint(name = "WebServiceSOAP")
    public WebServiceServer getWebServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://datawarehouse.laboratory.unitn.it", "WebServiceSOAP"), WebServiceServer.class, features);
    }

}
