
package it.unitn.laboratory.events;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Events", targetNamespace = "http://events.laboratory.unitn.it/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Events {


    /**
     * 
     * @param parameters
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendEvent", action = "http://events.laboratory.unitn.it/SendEvent")
    @WebResult(name = "EventNotificationResponse", targetNamespace = "http://events.laboratory.unitn.it/", partName = "parameters")
    public String sendEvent(
        @WebParam(name = "EventNotificationRequest", targetNamespace = "http://events.laboratory.unitn.it/", partName = "parameters")
        EventType parameters);

}
