package it.unitn.laboratory.wrapper;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-12T16:59:06.231+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "DwhWS", 
                  wsdlLocation = "http://192.168.1.41:9090/DwhWS?wsdl",
                  targetNamespace = "http://events.laboratory.unitn.it") 
public class DwhWS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://events.laboratory.unitn.it", "DwhWS");
    public final static QName DwhWSSOAP = new QName("http://events.laboratory.unitn.it", "DwhWSSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.41:9090/DwhWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DwhWS_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/DWH/services/DwhWSSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DwhWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DwhWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DwhWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns DwhWS
     */
    @WebEndpoint(name = "DwhWSSOAP")
    public DwhWS getDwhWSSOAP() {
        return super.getPort(DwhWSSOAP, DwhWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DwhWS
     */
    @WebEndpoint(name = "DwhWSSOAP")
    public DwhWS getDwhWSSOAP(WebServiceFeature... features) {
        return super.getPort(DwhWSSOAP, DwhWS.class, features);
    }

}
