package it.unitn.laboratory.wrapper;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-15T09:03:24.534+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "DwhWS", 
                  wsdlLocation = "http://192.168.1.41:9090/DwhWS?wsdl",
                  targetNamespace = "http://wrapper.laboratory.unitn.it")
public class DwhWS_Service
    extends Service
{

	public final static QName SERVICE = new QName("http://wrapper.laboratory.unitn.it", "DwhWS");
	public final static QName DwhWSSOAP = new QName("http://wrapper.laboratory.unitn.it", "DwhWSSOAP");
	private final static URL DWHWS_WSDL_LOCATION;
    private final static WebServiceException DWHWS_EXCEPTION;
    private final static QName DWHWS_QNAME = new QName("http://wrapper.laboratory.unitn.it", "DwhWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/michele/workspace/DWH/WebContent/wsdl/DwhWS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DWHWS_WSDL_LOCATION = url;
        DWHWS_EXCEPTION = e;
    }

    public DwhWS_Service() {
        super(__getWsdlLocation(), DWHWS_QNAME);
    }

    public DwhWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DWHWS_QNAME);
    }

    public DwhWS_Service(URL wsdlLocation) {
        super(wsdlLocation, DWHWS_QNAME);
    }

    public DwhWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DWHWS_QNAME);
    }

    public DwhWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DwhWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns DwhWS
     */
    @WebEndpoint(name = "DwhWSSOAP")
    public DwhWS getDwhWSSOAP() {
        return super.getPort(new QName("http://wrapper.laboratory.unitn.it", "DwhWSSOAP"), DwhWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DwhWS
     */
    @WebEndpoint(name = "DwhWSSOAP")
    public DwhWS getDwhWSSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://wrapper.laboratory.unitn.it", "DwhWSSOAP"), DwhWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DWHWS_EXCEPTION!= null) {
            throw DWHWS_EXCEPTION;
        }
        return DWHWS_WSDL_LOCATION;
    }

}
