//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.07 at 08:36:04 AM CET 
//


package it.unitn.laboratory.mappedData;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DwhSchemaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DwhSchemaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="D_ASSISTITO" type="{http:/it.unitn.laboratory.MappedEventsSchema}AssistitoType"/>
 *         &lt;element name="D_OPERATORE" type="{http:/it.unitn.laboratory.MappedEventsSchema}OperatoreType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DwhSchemaType", propOrder = {
    "dassistito",
    "doperatore"
})
public class DwhSchemaType {

    @XmlElement(name = "D_ASSISTITO", required = true)
    protected AssistitoType dassistito;
    @XmlElement(name = "D_OPERATORE", required = true)
    protected OperatoreType doperatore;

    /**
     * Gets the value of the dassistito property.
     * 
     * @return
     *     possible object is
     *     {@link AssistitoType }
     *     
     */
    public AssistitoType getDASSISTITO() {
        return dassistito;
    }

    /**
     * Sets the value of the dassistito property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssistitoType }
     *     
     */
    public void setDASSISTITO(AssistitoType value) {
        this.dassistito = value;
    }

    /**
     * Gets the value of the doperatore property.
     * 
     * @return
     *     possible object is
     *     {@link OperatoreType }
     *     
     */
    public OperatoreType getDOPERATORE() {
        return doperatore;
    }

    /**
     * Sets the value of the doperatore property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatoreType }
     *     
     */
    public void setDOPERATORE(OperatoreType value) {
        this.doperatore = value;
    }

}
