//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.07 at 09:28:09 AM CET 
//


package it.unitn.laboratory.mappedData;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EVENT_COD" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="EVENT_DESCR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventType", propOrder = {
    "eventcod",
    "eventdescr"
})
public class EventType {

    @XmlElement(name = "EVENT_COD")
    protected int eventcod;
    @XmlElement(name = "EVENT_DESCR", required = true)
    protected String eventdescr;

    /**
     * Gets the value of the eventcod property.
     * 
     */
    public int getEVENTCOD() {
        return eventcod;
    }

    /**
     * Sets the value of the eventcod property.
     * 
     */
    public void setEVENTCOD(int value) {
        this.eventcod = value;
    }

    /**
     * Gets the value of the eventdescr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEVENTDESCR() {
        return eventdescr;
    }

    /**
     * Sets the value of the eventdescr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEVENTDESCR(String value) {
        this.eventdescr = value;
    }

}
