//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.07 at 10:09:32 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://events.laboratory.unitn.it/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.unitn.laboratory.mappedData;
