
package it.unitn.laboratory.events;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Events", targetNamespace = "http://events.laboratory.unitn.it/", 
		wsdlLocation = "file:C:/Users/Matteo/workspace/ESBMediator/cxf-bc/Events.wsdl")
public class Events_Service
    extends Service
{

    private final static URL EVENTS_WSDL_LOCATION;
    private final static WebServiceException EVENTS_EXCEPTION;
    private final static QName EVENTS_QNAME = new QName("http://events.laboratory.unitn.it/", "Events");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:C:/Users/Matteo/workspace/ESBMediator/cxf-bc/Events.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EVENTS_WSDL_LOCATION = url;
        EVENTS_EXCEPTION = e;
    }

    public Events_Service() {
        super(__getWsdlLocation(), EVENTS_QNAME);
    }

    public Events_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EVENTS_QNAME, features);
    }

    public Events_Service(URL wsdlLocation) {
        super(wsdlLocation, EVENTS_QNAME);
    }

    public Events_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EVENTS_QNAME, features);
    }

    public Events_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Events_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Events
     */
    @WebEndpoint(name = "EventsSOAP")
    public Events getEventsSOAP() {
        return super.getPort(new QName("http://events.laboratory.unitn.it/", "EventsSOAP"), Events.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Events
     */
    @WebEndpoint(name = "EventsSOAP")
    public Events getEventsSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://events.laboratory.unitn.it/", "EventsSOAP"), Events.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EVENTS_EXCEPTION!= null) {
            throw EVENTS_EXCEPTION;
        }
        return EVENTS_WSDL_LOCATION;
    }

}
