
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.unitn.laboratory.wrapper;



import it.unitn.laboratory.adapter.EventManager;

import java.util.logging.Logger;
import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-15T09:03:24.448+01:00
 * Generated source version: 2.5.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "DwhWS",
                      portName = "DwhWSSOAP",
                      targetNamespace = "http://wrapper.laboratory.unitn.it",
                      // wsdlLocation = "http://192.168.1.41:9090/DwhWS?wsdl",
                      endpointInterface = "it.unitn.laboratory.wrapper.DwhWS")
                      
public class DwhWSImpl implements DwhWS {

    private static final Logger LOG = Logger.getLogger(DwhWSImpl.class.getName());

    /* (non-Javadoc)
     * @see it.unitn.laboratory.wrapper.DwhWS#sendMappedChanges(it.unitn.laboratory.wrapper.DwhSchemaType  dwhSCHEMA )*
     */
    public java.lang.String sendMappedChanges(DwhSchemaType dwhSCHEMA) 
    { 
        
        int type = dwhSCHEMA.getEVENTTYPE().getEVENTCOD();
        LOG.info("Executing operation "+dwhSCHEMA.getEVENTTYPE().getEVENTDESCR());
        switch ( type ) 
        {
			case 1:	 return EventManager.inserimentoVariazioneAnagrafica(dwhSCHEMA);
			case 2:  return EventManager.inserimentoVariazioneNucleoFatto(dwhSCHEMA);
			case 3:  return EventManager.inserimentoSchedaAccesso(dwhSCHEMA);
			case 4:  return EventManager.presaInCarico(dwhSCHEMA);
			case 6:  return EventManager.assegnazioneAreaUtenza(dwhSCHEMA);
			case 7:  return EventManager.revocaAreaUtenza(dwhSCHEMA);
			default: return "ERROR: type "+type+" not supported yet. I'm so sorry";
		}        
    }
    
    public static void main(String[] args){
    	Endpoint.publish("http://192.168.1.41:9090/DwhWS",new DwhWSImpl());
    }



}
