
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.unitn.laboratory.wrapper;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-03-07T14:15:56.650+01:00
 * Generated source version: 2.5.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "DwhWS",
                      portName = "DwhWSSOAP",
                      targetNamespace = "http://events.laboratory.unitn.it",
                      wsdlLocation = "http://192.168.1.41:9090/DwhWS?wsdl",
                      endpointInterface = "it.unitn.laboratory.wrapper.DwhWS")
                      
public class DwhWSImpl implements DwhWS {

    private static final Logger LOG = Logger.getLogger(DwhWSImpl.class.getName());

    /* (non-Javadoc)
     * @see it.unitn.laboratory.wrapper.DwhWS#sendMappedChanges(it.unitn.laboratory.wrapper.DwhSchemaType  dwhSCHEMA )*
     */
    public java.lang.String sendMappedChanges(it.unitn.laboratory.wrapper.DwhSchemaType dwhSCHEMA) { 
        LOG.info("Executing operation sendMappedChanges");
        System.out.println(dwhSCHEMA);
        try {
            java.lang.String _return = "_return-943519274";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
